Inc2SuchTrans/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inc2SuchTrans.Models;
using Inc2SuchTrans.BLL;
using Inc2SuchTrans.CustomFilters;
using System.Data.Entity;

namespace Inc2SuchTrans.Controllers
{
    public class DriverController : BaseController
    {
        STLogisticsEntities db = new STLogisticsEntities();
        // GET: Driver
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [AuthLog(Roles = "Admin, Driver")]
        public ActionResult SearchDelivery()
        {
            //if (String.IsNullOrEmpty(refkey))
            //{
            //    Information("Please Enter A Delivery Reference Key");
            //    return View();

            //else
            //{
            //    try
            //    {
            //        Delivery del = db.Delivery.Where(x => x.DeliveryRef == refkey).FirstOrDefault();
            //        if (del != null)
            //        {
            //            return RedirectToAction("DeliveryDetails", new { id = del.DelID });
            //        }
            //        else
            //        {
            //            Danger("Invalid Reference Key. Please make sure you have a valid key");
            //            return View();
            //        }
            //    }
            //    catch (Exception e)
            //    {
            //        Danger("Oops!! Something went wrong.. Please contact support. <br> Error: " + e.Message + "<br> StackTrace: " + e.StackTrace);
            //        return View();
            //    }
            //}

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="refkey"></param>
        /// <returns></returns>
        [AuthLog(Roles = "Admin, Driver")]
        public ActionResult DeliveryDetails(string refkey)
        {
            if (String.IsNullOrEmpty(refkey))
            {
                try
                {
                    Information("Please Enter A Delivery Reference Key");
                    return RedirectToAction("SearchForDelivery");
                }
                catch (Exception e)
                {
                    Danger("Oops! Something went wrong..<br> Please contact support");
                    return View();
                    throw e;
                }
            }
            else
            {
                try
                {
                    Delivery del = db.Delivery.Where(x => x.DeliveryRef == refkey).SingleOrDefault();
                    if (del != null)
                    {
                        return View(del);
                    }
                    else
                    {
                        Danger("The reference key you have entered is not valid.. <br> Please make sure you have a valid reference key or contact support");
                        return RedirectToAction("SearchForDelivery");
                    }
                }
                catch (Exception e)
                {
                    Danger("Oops! Something went wrong..<br> Please contact support");
                    return View();
                    throw e;
                }
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AuthLog(Roles = "Admin, Driver")]
        public ActionResult Edit(int id)
        {
            try
            {
                Delivery del = db.Delivery.Find(id);
                if (del != null)
                {
                    return View(del);
                }
                else
                {
                    Danger("Error retrieving Delivery");
                    return View();
                }
            }
            catch (Exception e)
            {
                Danger("Oops!! Something went wrong.. Please contact support. <br> Error: " + e.Message + "<br> StackTrace: " + e.StackTrace);
                return View();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AuthLog(Roles = "Admin, Driver")]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "DelID,CustomerID,CurrentDate,DeliveryDate,PickUpArea,DropOffArea,DropOffAdd,CargoSize,CargoWeight,TotalCost,Paid,DeliveryRef,DeliveryStatus")] Delivery delivery)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(delivery).State = EntityState.Modified;
                    Deliveryjob dj = db.Deliveryjob.Where(x => x.DelID == delivery.DelID).FirstOrDefault();
                    if (dj != null)
                    {
                        dj.JobStatus = delivery.DeliveryStatus;
                        db.Entry(dj).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                    return RedirectToAction("DeliveryJobs", "Admin");
                }
                catch (Exception e)
                {
                    Danger("Oops!! Something went wrong.. Please contact support. <br> Error: " + e.Message + "<br> StackTrace: " + e.StackTrace);
                    return View();
                }
            }
            return View(delivery);
        }
    }
}

Inc2SuchTrans/Views/Driver/DeliveryDetails.cshtml
@model Inc2SuchTrans.Models.Delivery
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<br />

        <h1 class="EveryHeader">Delivery Details</h1>
<div class="FilterDivAdmin">
    <div>
        @{ Html.RenderPartial("_Alerts"); }


        <table class="table-condensed table-bordered BookingTable">
            <tbody>
                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CurrentDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CurrentDate)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DeliveryDate)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.PickUpArea)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.PickUpArea)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DropOffArea)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DropOffArea)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DropOffAdd)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DropOffAdd)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CargoSize)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CargoSize)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CargoWeight)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CargoWeight)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.TotalCost)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.TotalCost)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.Paid)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Paid)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryRef)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DeliveryRef)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryStatus)
                    </td>
                    <td class="alert-info">
                        @Html.DisplayFor(model => model.DeliveryStatus)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="OrangeButton">
        @Html.ActionLink("Notify of Pick Up", "Edit", new { id = Model.DelID }, new { @class="OrangeButtonLink"}) @*<br />
            @Html.ActionLink("Notify of Drop Off", "Edit")*@
    </div>
</div>

Inc2SuchTrans/Views/Driver/Edit.cshtml
@model Inc2SuchTrans.Models.Delivery

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

            <h1 class="EveryHeader">Pick-up or Drop-off</h1>
<div class="FilterDivAdmin">
    @using (Html.BeginForm())
    {
        <div class="form-horizontal">
            <hr />
            @Html.HiddenFor(model => model.DelID)
            @Html.HiddenFor(model => model.CustomerID)
            @Html.HiddenFor(model => model.CurrentDate)
            @Html.HiddenFor(model => model.DeliveryDate)
            @Html.HiddenFor(model => model.PickUpArea)
            @Html.HiddenFor(model => model.DropOffArea)
            @Html.HiddenFor(model => model.DropOffAdd)
            @Html.HiddenFor(model => model.CargoSize)
            @Html.HiddenFor(model => model.CargoWeight)
            @Html.HiddenFor(model => model.TotalCost)
            @Html.HiddenFor(model => model.Paid)
            @Html.HiddenFor(model => model.DeliveryRef)


            <table class="BookingTable">
                <tr>
                    <td>
                @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2 Column1" })
                    </td>
                    <td>
                    @Html.TextBoxFor(model => model.CustomerID, new { disabled = "disabled" })
                    </td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.CurrentDate, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.CurrentDate, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DeliveryDate, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.DeliveryDate, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.PickUpArea, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.PickUpArea, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DropOffArea, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.DropOffArea, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DropOffAdd, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.DropOffAdd, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.CargoSize, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.CargoSize, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.CargoWeight, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.CargoWeight, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.TotalCost, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.TotalCost, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.Paid, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DeliveryRef, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.TextBoxFor(model => model.DeliveryRef, new { disabled = "disabled" })</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DeliveryStatus, htmlAttributes: new { @class = "control-label col-md-2 Column1" })</td>
                    <td>@Html.DropDownListFor(model => model.DeliveryStatus, new SelectList(new List<Object> {
                                                                                new {value="En-route", text="Picked Up"},
                                                                                new {value="Delivered", text="Dropped Off"}
                                                                                },
                                           "value", "text"))</td>
                </tr>
               

            </table>
                    <input type="submit" value="Save" class="OrangeButton" />
            
    <div>
        @Html.ActionLink("Back to Details", "DeliveryDetails", new { refkey = Model.DeliveryRef })
    </div>

</div>
    }

Inc2SuchTrans/Views/Driver/SearchDelivery.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<br />
<br />
                <h1 class="EveryHeader">Search For A Delivery</h1>
<div class="FilterDivAdmin">
    @{ Html.RenderPartial("_Alerts"); }
    @using (Html.BeginForm("DeliveryDetails", "Driver", FormMethod.Post))
    {
        
                <div class="search">
                    @*<input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key"/>*@
                    <input type="text" class="form-control input-sm" id="refkey" name="refkey" maxlength="64" placeholder="Enter Delivery Reference Key" />
                    <button type="submit" class="btn btn-primary btn-sm">Search</button>
                </div>
           

        @*<div class="container">
                <div class="row">
                    <h4>Search For A Delivery</h4>
                    <div class="search">
                        <input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key" />
                        <button type="submit" class="btn btn-primary btn-sm">Search</button>
                    </div>
                </div>
            </div>*@
    }
</div>