Inc2SuchTrans/Controllers/latsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Inc2SuchTrans.Models;

namespace mapslatlong1.Controllers
{
    public class latsController : Controller
    {
        private STLogisticsEntities db = new STLogisticsEntities();

        // GET: lats
        public ActionResult Index()
        {
            return View(db.TrackDelivery.ToList());
        }


        // GET: lats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrackDelivery lat = db.TrackDelivery.Find(id);
            if (lat == null)
            {
                return HttpNotFound();
            }
            return View(lat);
        }

        // GET: lats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: lats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,latituide,longitude")] TrackDelivery lat)
        {
            if (ModelState.IsValid)
            {
                db.TrackDelivery.Add(lat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lat);
        }

        // GET: lats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrackDelivery lat = db.TrackDelivery.Find(id);
            if (lat == null)
            {
                return HttpNotFound();
            }
            return View(lat);
        }

        // POST: lats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,latituide,longitude")] TrackDelivery lat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lat);
        }

        // GET: lats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrackDelivery lat = db.TrackDelivery.Find(id);
            if (lat == null)
            {
                return HttpNotFound();
            }
            return View(lat);
        }

        // POST: lats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TrackDelivery lat = db.TrackDelivery.Find(id);
            db.TrackDelivery.Remove(lat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Inc2SuchTrans/Views/lats/Create.cshtml
@model Inc2SuchTrans.Models.TrackDelivery

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Enter latuide and longitude</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inc2SuchTrans/Views/lats/Delete.cshtml
@model Inc2SuchTrans.Models.TrackDelivery

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<div class="FilterDivAdmin">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>lat</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Latitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Latitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Longitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Longitude)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="OrangeButton" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

Inc2SuchTrans/Views/lats/Details.cshtml
@model Inc2SuchTrans.Models.TrackDelivery

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Details";
}

<h2 class="EveryHeader">Details</h2>
<div class="FilterDivAdmin">
    <div>
        <h4>lat</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Latitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Latitude)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Longitude)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Longitude)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.TrackID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Inc2SuchTrans/Views/lats/Edit.cshtml
@model Inc2SuchTrans.Models.TrackDelivery

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<div class="FilterDivAdmin">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>lat</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.TrackID)

            <div class="form-group">
                @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inc2SuchTrans/Views/lats/Index.cshtml
@model IEnumerable<Inc2SuchTrans.Models.TrackDelivery>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Index";
}

<div style="font-family:Arial">

    <h2 class="EveryHeader">Index</h2>
    <div class="FilterDivAdmin"style="width:75%; margin:0px auto;">
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>

        @using (Html.BeginForm("Index", "lats", FormMethod.Get))
        {


            <b>Search using id:</b><br /> @Html.RadioButton("searchby", "id")
            <text>ID</text><br />
            @Html.TextBox("search");
            <input type="submit" value="search" />


        }
        <br />

        <table class="DeliveryTable table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Latitude)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Longitude)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Latitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Longitude)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.TrackID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.TrackID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.TrackID })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>