Inc2SuchTrans/Models/Delivery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.Deliveryjob = new HashSet<Deliveryjob>();
        }
    
        public int DelID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PickUpArea { get; set; }
        public string DropOffArea { get; set; }
        public string DropOffAdd { get; set; }
        public Nullable<int> CargoSize { get; set; }
        public Nullable<decimal> CargoWeight { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string DeliveryRef { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<decimal> DiscountCost { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliveryjob> Deliveryjob { get; set; }
    }
}

Inc2SuchTrans/Models/TrackDelivery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inc2SuchTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackDelivery
    {
        public int TrackID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
    
        public virtual Deliveryjob Deliveryjob { get; set; }
    }
}

Inc2SuchTrans/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inc2SuchTrans.BLL;
using Inc2SuchTrans.Models;
using System.Globalization;
using Microsoft.AspNet.Identity;
using System.Text;
using Inc2SuchTrans.CustomFilters;
using System.Net.Mail;
using System.IO;
using HiQPdf;
using System.Data.Entity;

namespace Inc2SuchTrans.Controllers
{
    public class DeliveryController : BaseController
    {
        DeliveryLogic logic = new DeliveryLogic();
        QuoteLogic qlogic = new QuoteLogic();
        CustomerLogic custLogic = new CustomerLogic();
        CargoLogic clogic = new CargoLogic();
        AreaRateLogic arlogic = new AreaRateLogic();
        DeliveryJobLogic djlogic = new DeliveryJobLogic();
        ArchiveLogic arclogic = new ArchiveLogic();
        TruckDriverLogic tdlogic = new TruckDriverLogic();
        FleetLogic flogic = new FleetLogic();

        //byte[] pdfBuffer;

        STLogisticsEntities db = new STLogisticsEntities();

        // GET: Delivery
        public ActionResult Index()
        {
            try
            {
                List<Delivery> del = logic.returnAllDeliveries();
                return View(del);
            }
            catch (Exception e)
            {
                Danger("Unfortunately something went wrong.. <br> Could not retrieve list, Please contact support");
                return View();
                throw e;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AuthLog(Roles = "Admin")]
        public ActionResult UpdateDeliveryJobStatus(int id)
        {
            try
            {
                Deliveryjob dj = db.Deliveryjob.Find(id);
                return View(dj);
            }
            catch (Exception e)
            {
                Danger("Unfortunately something went wrong.. <br>Please contact support <br>Error: " + e.Message + "<br> StackTrace: " + e.StackTrace);
                return View();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [AuthLog(Roles = "Admin")]
        public ActionResult UpdateDeliveryJobStatus([Bind(Include = "JobID,DelID,TruckID,DriverID,JobStatus,PortDelay")] Deliveryjob dj)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(dj).State = EntityState.Modified;
                    //db.SaveChanges();

                    Delivery del = db.Delivery.Where(x => x.DelID == dj.DelID).FirstOrDefault();
                    del.DeliveryStatus = dj.JobStatus;
                    db.Entry(del).State = EntityState.Modified;

                    if (dj.JobStatus.ToLower() == "delivered")
                    {
                        JobQueue jq = db.JobQueue.Where(x => x.JobID == dj.JobID).FirstOrDefault();
                        if (jq != null)
                        {
                            db.JobQueue.Attach(jq);
                            db.JobQueue.Remove(jq);

                            TruckDriver td = db.TruckDriver.Where(x => x.DriverID == dj.DriverID).FirstOrDefault();
                            Fleet truck = db.Fleet.Where(x => x.TruckId == dj.TruckID).FirstOrDefault();

                            td.Avail = true;
                            truck.Availability = true;

                            db.Entry(td).State = EntityState.Modified;
                            db.Entry(truck).State = EntityState.Modified;
                        }
                    }
                    db.SaveChanges();

                    return RedirectToAction("DeliveryJobs", "Admin");
                }
                catch (Exception e)
                {
                    Danger("Oops!! Something went wrong.. Please contact support. <br> Error: " + e.Message + "<br> StackTrace: " + e.StackTrace);
                    return View();
                }
            }
            else
            {
                ViewBag.DelID = new SelectList(db.Delivery, "DelID", "PickUpArea", dj.DelID);
                ViewBag.DriverID = new SelectList(db.TruckDriver, "DriverID", "DriverID", dj.DriverID);
                ViewBag.TruckID = new SelectList(db.Fleet, "TruckId", "TruckNumberPlate", dj.TruckID);
                return View(dj);
            }
        }

        //TODO : Selected - RED and CHANGE TO label will have drop down next to it.
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [AuthLog(Roles = "Customer")]
        [HttpGet]
        public ActionResult CreateFromEmail()
        {
            IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
            {
                Value = c.Area,
                Text = c.Area
            });

            IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
            {
                Value = c.PickUpArea,
                Text = c.PickUpArea
            });
            ViewBag.DropOffArea = dropOff;
            ViewBag.PickUpArea = pickUp;
            return View();

        }
        [AuthLog(Roles = "Customer")]
        [HttpGet]
        public ActionResult CreateFromQuote(int? id)
        {
            Quote q = qlogic.searchQuote(id);
            Delivery del = new Delivery();
            del.PickUpArea = q.PickUpArea;
            del.DropOffArea = q.DropOffArea;
            del.CargoSize = q.CargoSize;
            del.CargoWeight = q.CargoWeight;
            ViewBag.QID = id;
            return View(del);
        }
        [AuthLog(Roles = "Customer")]
        [HttpPost]
        public ActionResult CreateFromQuote(string userId, string DeliveryDate, string PickUpArea, string DropOffArea, string DropOffAdd, string CargoSize, string CargoWeight, int QuoteID)
        {
            var CurrentCustomer = HttpContext.User.Identity.Name;
            var CustT = db.Customer.ToList().Find(x => x.Email == CurrentCustomer);
            if (String.IsNullOrEmpty(userId))
            {
                userId = User.Identity.GetUserId();
            }
            ViewBag.QID = QuoteID;
            Quote q = qlogic.searchQuote(QuoteID);
            Delivery olddel = new Delivery();
            olddel.PickUpArea = q.PickUpArea;
            olddel.DropOffArea = q.DropOffArea;
            olddel.CargoSize = q.CargoSize;
            olddel.CargoWeight = q.CargoWeight;

            if (String.IsNullOrEmpty(DeliveryDate))
            {
                Danger("Please Enter A Delivery Date");
                IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
                {
                    Value = c.Area,
                    Text = c.Area
                });

                IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
                {
                    Value = c.PickUpArea,
                    Text = c.PickUpArea
                });
                ViewBag.DropOffArea = dropOff;
                ViewBag.PickUpArea = pickUp;
                return View(olddel);
            }
            if (System.Convert.ToDateTime(DeliveryDate) <= DateTime.Today)
            {
                Danger("Delivery Date is Invalid, Please Try Again");
                IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
                {
                    Value = c.Area,
                    Text = c.Area
                });

                IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
                {
                    Value = c.PickUpArea,
                    Text = c.PickUpArea
                });
                ViewBag.DropOffArea = dropOff;
                ViewBag.PickUpArea = pickUp;
                return View(olddel);
            }
            if (String.IsNullOrEmpty(PickUpArea))
            {
                Danger("Please Enter A Delivery Date");
                IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
                {
                    Value = c.Area,
                    Text = c.Area
                });

                IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
                {
                    Value = c.PickUpArea,
                    Text = c.PickUpArea
                });
                ViewBag.DropOffArea = dropOff;
                ViewBag.PickUpArea = pickUp;
                return View(olddel);
            }
            if (String.IsNullOrEmpty(DropOffArea))
            {
                Danger("Please Enter A Delivery Date");
                IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
                {
                    Value = c.Area,
                    Text = c.Area
                });

                IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
                {
                    Value = c.PickUpArea,
                    Text = c.PickUpArea
                });
                ViewBag.DropOffArea = dropOff;
                ViewBag.PickUpArea = pickUp;
                return View(olddel);
            }
            if (String.IsNullOrEmpty(DropOffAdd))
            {
                Danger("Please Enter A Delivery Date");
                IEnumerable<SelectListItem> dropOff = db.AreaRates.Select(c => new SelectListItem
                {
                    Value = c.Area,
                    Text = c.Area
                });

                IEnumerable<SelectListItem> pickUp = db.Cargo.Select(c => new SelectListItem
                {
                    Value = c.PickUpArea,
                    Text = c.PickUpArea
                });
                ViewBag.DropOffArea = dropOff;
                ViewBag.PickUpArea = pickUp;
                return View(olddel);
            }

Inc2SuchTrans/Views/Delivery/CancelPF.cshtml
@{ 

}

<div class="FilterDiv">
    <div>
        @{ Html.RenderPartial("_Alerts"); }
    </div>
    
    <br />
    <div>
        @Html.ActionLink("Back To Deliveries", "YourDeliveries")
    </div>
    

</div>

Inc2SuchTrans/Views/Delivery/CreateFromQuote.cshtml
@model Inc2SuchTrans.Models.Delivery
@section scripts
{
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBA13dZ85nJ866fueX4lhX_s83xVrejErY&libraries=places"></script>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Delivery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DelID)

        <div class="FilterDiv">
            <hr />
            <table class="BookingTable">
                <tr>
                    <td><strong>Delivery Date</strong></td>
                    <td>@Html.EditorFor(model => model.DeliveryDate, new { htmlAttributes = new { @id = "DeliveryDate" } })
                    @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td><strong>Pick Up Area</strong></td>
                    <td>@Html.TextBoxFor(model => model.PickUpArea, new { @readonly = "readonly", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PickUpArea, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td><strong>Drop Off Area</strong></td>
                    <td>@Html.TextBoxFor(model => model.DropOffArea, new { @readonly = "readonly", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.DropOffArea, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td><strong>Drop Off Address</strong></td>
                    <td>@Html.EditorFor(model => model.DropOffAdd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DropOffAdd, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td><strong>Cargo Size</strong></td>
                    <td>@Html.TextBoxFor(model => model.CargoSize, new { @readonly = "readonly", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CargoSize, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <td><strong>Cargo Weighte</strong></td>
                    <td>@Html.TextBoxFor(model => model.CargoWeight, new { @readonly = "readonly", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CargoWeight, "", new { @class = "text-danger" })</td>
                </tr>
            </table>

 

           

            <input type="hidden" name="QuoteID" value="@ViewBag.QID" />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
        </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Inc2SuchTrans/Views/Delivery/DeliveryStatus.cshtml
@model Inc2SuchTrans.Models.Delivery
@{

}



<br />

                    <h4 style="font-size:300%; text-decoration:underline;text-align:center;">Search For A Delivery</h4>
<div class="FilterDiv">
    <div>
        @using (Html.BeginForm("DeliveryStatus", "Delivery", FormMethod.Get))
        {
            <div class="container">
                <div class="row">
                    <div class="search">
                        @*<input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key"/>*@
                        <input type="text" class="form-control input-sm" id="refkey" name="refkey" maxlength="64" placeholder="Enter Delivery Reference Key" />
                        <button type="submit" class="btn btn-primary btn-sm">Search</button>
                    </div>
                </div>
            </div>

            @*<div class="container">
                    <div class="row">
                        <h4>Search For A Delivery</h4>
                        <div class="search">
                            <input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key" />
                            <button type="submit" class="btn btn-primary btn-sm">Search</button>
                        </div>
                    </div>
                </div>*@
        }
        <h4>Delivery Details</h4>
        @{ Html.RenderPartial("_Alerts"); }

        <hr />

        <table class="table-condensed table-bordered DeliveryTable">
            <tbody>
                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CurrentDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CurrentDate)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryDate)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DeliveryDate)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.PickUpArea)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.PickUpArea)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DropOffArea)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DropOffArea)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DropOffAdd)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DropOffAdd)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CargoSize)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CargoSize)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.CargoWeight)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.CargoWeight)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.TotalCost)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.TotalCost)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.Paid)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Paid)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryRef)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.DeliveryRef)
                    </td>
                </tr>

                <tr>
                    <td class="alert-info">
                        @Html.DisplayNameFor(model => model.DeliveryStatus)
                    </td>
                    <td class="alert-info">
                        @Html.DisplayFor(model => model.DeliveryStatus)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <p>
        @Html.ActionLink("Back To Deliveries", "YourDeliveries") |
        @Html.ActionLink("Track Delivery", "TrackDelivery", new { id = Model.DelID }) |
        @Html.ActionLink("Cancel Delivery", "CancelDelivery", new { id = Model.DelID }) | <br/>
        @Html.ActionLink("Change Destination", "ChangeDestination", new { id=Model.DelID})
    </p>
</div>

Inc2SuchTrans/Views/Delivery/EmailPaperwork.cshtml
@model Inc2SuchTrans.Models.MailModel
@{

}


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="FilterDiv" style="color:black">
            <h4 style="color:white">Send Email:</h4>
            <table class="QuoteTable">
                <thead style="color:white;"></thead>
                <tbody>
                    <tr>
                        <td class="alert-success QuoteTableTD">
                            @Html.LabelFor(model => model.To, new { style = "display:inline;" })
                        </td>
                        <td class="QuoteTableTD">
                            <p>@Html.TextBoxFor(m => m.To, new { @Value = User.Identity.Name })</p>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Send" class="btn btn-primary" />
                </div>
            </div>
            <div>
                @Html.ActionLink("Cancel", "YourDeliveries", "Delivery")
            </div>
        </div>
    </div>
}
@{ Html.RenderPartial("_Alerts"); }

Inc2SuchTrans/Views/Delivery/Index.cshtml
@model IEnumerable<Inc2SuchTrans.Models.Delivery>

@{

}

@{ Html.RenderPartial("_Alerts"); }
<h1><strong>All Deliveries</strong></h1>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="FilterDivv2">
    <table class="DeliveryTable">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryRef)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PickUpArea)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DropOffArea)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DropOffAdd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CargoSize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CargoWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Paid)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryRef)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PickUpArea)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DropOffArea)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DropOffAdd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CargoSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CargoWeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalCost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Paid)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.DelID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.DelID })
                </td>
            </tr>
        }

    </table>
</div>

Inc2SuchTrans/Views/Delivery/SearchForDelivery.cshtml
@{

}


                <h4 style="font-size:300%; text-decoration:underline;text-align:center;">Search For A Delivery</h4>
<div class="FilterDiv">
    @{ Html.RenderPartial("_Alerts"); }
    @using (Html.BeginForm("DeliveryStatus", "Delivery", FormMethod.Post))
    {
        
            
                
                    @*<input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key"/>*@
                    <p>Enter your Delivery Reference Key</p>
                    <input type="text" class="form-control input-sm" id="refkey" name="refkey" maxlength="64" placeholder="Enter Delivery Reference Key" />
                    <button type="submit" style="margin-left:auto; margin-right: auto; background-color:lightblue; margin:2px;">Search</button>
                

        @*<div class="container">
                <div class="row">
                    <h4>Search For A Delivery</h4>
                    <div class="search">
                        <input type="text" class="form-control input-sm" maxlength="64" placeholder="Enter Delivery Reference Key" />
                        <button type="submit" class="btn btn-primary btn-sm">Search</button>
                    </div>
                </div>
            </div>*@
    }
</div>

Inc2SuchTrans/Views/Delivery/UnpaidDeliveries.cshtml
@model IEnumerable<Inc2SuchTrans.Models.Delivery>

@{ 

}

@using (Html.BeginForm("UnpaidDeliveries", "Delivery", FormMethod.Post))
{
    @*<div class="container FilterDiv">
        <div class="row">
            <h4>Search For A Delivery</h4>
            <div class="search">
                @Html.Editor("refkey")
                <button type="submit" class="btn btn-primary btn-sm">Search</button>
            </div>
        </div>
    </div>*@

            <h4 style="font-size:300%;text-decoration:underline; text-align:center;">Unpaid Deliveries</h4>
    <div class="container FilterDivv2">
        <div class="row">
            <div class="search">
                <input type="text" class="form-control input-sm" id="refkey" name="refkey" maxlength="64" placeholder="Enter Delivery Reference Key" />
                <button type="submit" class="btn btn-primary btn-sm">Search</button>
            </div>
        </div>




        @{ Html.RenderPartial("_Alerts"); }

        <table class="DeliveryTable">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DeliveryRef)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CurrentDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DeliveryDate)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.PickUpArea)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DropOffArea)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.DropOffAdd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CargoSize)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.CargoWeight)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.TotalCost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Paid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Customer.IDNumber)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryRef)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeliveryDate)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.PickUpArea)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DropOffArea)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.DropOffAdd)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CargoSize)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.CargoWeight)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Paid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Customer1.IDNumber)
                    </td>
                    <td>
                        <div class="OrangeButton">
                            @Html.ActionLink("Pay Now", "ConfirmOrder", new { id = item.DelID }, new { @class = "OrangeButtonLink"})
                        </div>
                    </td>
                </tr>
            }
            
                

        </table>

                    @Html.ActionLink("Back", "YourDeliveries")
    </div>
            }